### ISSUE TITLE
Learn how to use Inkscape

### ISSUE THREAD

**Issue by JEC-SCHOOL** [rewolf93/CS370#23]

**Comment by JEC-SCHOOL** [comment]
Inkscape uses the SVG (Scalable Vector Graphics) format for its files. SVG is an open standard widely supported by graphic software. SVG files are based on XML and can be edited with any text or XML editor (apart from Inkscape, that is). Besides SVG, Inkscape can import and export several other formats (EPS, PNG).

**Comment by JEC-SCHOOL** [comment]
I can make squares now. we're making progress!

**Comment by JEC-SCHOOL** [comment]
[https://inkscape.org/learn/tutorials/](url)

**Comment by rewolf93** [comment]
@JEC-SCHOOL I followed your link and looked into SVG files. The looked really promising so I googled it real quick and found [this doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) explaining the whole paths thing. Good work! See if you can figure out how we can write a plugin to label different elements somehow. If we can label the stuff and tkinter plays nice with the format, this will probably be what we use

**Comment by JEC-SCHOOL** [comment]
Will be putting up wiki with all gathered information
