### ISSUE TITLE
Research PyGame

### ISSUE THREAD

**Issue by rewolf93** [rewolf93/CS370#30]

**Comment by pathhh** [comment]
I'm going to compile a list of resources that address some potential problems we will run into. I'll add more as I learn more. 

[Surfaces and Drawing](http://thepythongamebook.com/en:pygame:step003)

[Color](http://thepythongamebook.com/en:pygame:step004)

[Load Images](http://thepythongamebook.com/en:pygame:step007)

[TIle-Based Graphics ](http://thepythongamebook.com/en:pygame:step009)

[Sound](http://thepythongamebook.com/en:pygame:step010)

[Collision Detection ](http://thepythongamebook.com/en:pygame:step018)

**Comment by pathhh** [comment]
Also, while this may not be relevant, it seems [Pygame can be used in conjunction with Tkinter.](http://grapevine.com.au/~wisteria/tkfront/pygame_tkinter.html)

**Comment by rewolf93** [comment]
PyGame is now acting as the backbone of our game. Thanks for doing the research to get us going.
