### ISSUE TITLE
Play a sound

### ISSUE THREAD

**Issue by rewolf93** [rewolf93/CS370#41]
**Describe the solution you'd like**
The game should play a sound under certain conditions.

**Describe alternatives you've considered**
The basic problem can be playing a sound when a button is clicked.

**Comment by rewolf93** [comment]
Playing a sound in PyGame is described in #30

**Comment by pathhh** [comment]
[This may be helpful,](https://www.pygame.org/docs/ref/music.html) although it seems more geared to background music.
